lib/prediction_analyzer_web/router.ex
defmodule PredictionAnalyzerWeb.Router do
  use PredictionAnalyzerWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", PredictionAnalyzerWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/vehicle_events", VehicleEventsController, :index)
    get("/accuracy", AccuracyController, :index)
    get("/missed_predictions", MissedPredictionsController, :index)
    get("/predictions", PredictionsController, :csv)
    get("/_health", HealthController, :index)
  end

  scope "/accuracy", PredictionAnalyzerWeb do
    pipe_through(:browser)
    get("/subway", AccuracyController, :subway)
    get("/csv", AccuracyController, :csv)
    get("/commuter_rail", AccuracyController, :commuter_rail)
  end

  # Other scopes may use custom stacks.
  # scope "/api", PredictionAnalyzerWeb do
  #   pipe_through :api
  # end
end

lib/prediction_analyzer/missed_predictions.ex
defmodule PredictionAnalyzer.MissedPredictions do
  import Ecto.Query, only: [from: 2]
  alias PredictionAnalyzer.VehicleEvents.VehicleEvent
  alias PredictionAnalyzer.Predictions.Prediction
  alias PredictionAnalyzer.Filters.StopGroups
  alias PredictionAnalyzer.StopNameFetcher
  import Utilities.Time, only: [format_unix: 1]

  def unpredicted_departures_summary(date, env) do
    {min_time, max_time} = service_times(date)

    unpredicted_departures_query =
      from(ve in VehicleEvent,
        as: :vehicle_event,
        where:
          not is_nil(ve.trip_id) and
            not is_nil(ve.departure_time) and
            not ve.is_deleted and
            ve.environment == ^env and
            ve.departure_time >= ^min_time and
            ve.departure_time <= ^max_time and
            ve.stop_id in ^terminal_stops(),
        group_by: ve.route_id,
        select:
          {ve.route_id, count(ve.id),
           count(ve.id)
           |> filter(
             not exists(
               from(p in Prediction,
                 where:
                   p.vehicle_event_id == parent_as(:vehicle_event).id and
                     p.file_timestamp < parent_as(:vehicle_event).departure_time and
                     not is_nil(p.departure_time)
               )
             )
           ),
           (count(ve.id)
            |> filter(
              not exists(
                from(p in Prediction,
                  where:
                    p.vehicle_event_id == parent_as(:vehicle_event).id and
                      p.file_timestamp < parent_as(:vehicle_event).departure_time and
                      not is_nil(p.departure_time)
                )
              )
            )) * 100.0 / count(ve.id)}
      )

    unpredicted_departures_query
    |> PredictionAnalyzer.Repo.all()
    |> Enum.sort_by(&Map.get(sort_map(), elem(&1, 0), 0))
  end

  def unpredicted_departures_for_route(date, env, route_id) do
    {min_time, max_time} = service_times(date)

    unpredicted_departures_query =
      from(ve in VehicleEvent,
        as: :vehicle_event,
        where:
          not is_nil(ve.trip_id) and
            not is_nil(ve.departure_time) and
            not ve.is_deleted and
            ve.environment == ^env and
            ve.departure_time >= ^min_time and
            ve.departure_time <= ^max_time and
            ve.stop_id in ^terminal_stops() and
            ve.route_id == ^route_id,
        group_by: ve.stop_id,
        order_by: ve.stop_id,
        select:
          {ve.stop_id, count(ve.id),
           count(ve.id)
           |> filter(
             not exists(
               from(p in Prediction,
                 where:
                   p.vehicle_event_id == parent_as(:vehicle_event).id and
                     p.file_timestamp < parent_as(:vehicle_event).departure_time and
                     not is_nil(p.departure_time)
               )
             )
           ),
           (count(ve.id)
            |> filter(
              not exists(
                from(p in Prediction,
                  where:
                    p.vehicle_event_id == parent_as(:vehicle_event).id and
                      p.file_timestamp < parent_as(:vehicle_event).departure_time and
                      not is_nil(p.departure_time)
                )
              )
            )) * 100.0 / count(ve.id)}
      )

    unpredicted_departures_query
    |> PredictionAnalyzer.Repo.all()
    |> add_stop_names()
  end

  def unpredicted_departures_for_route_stop(date, env, route_id, stop_id) do
    {min_time, max_time} = service_times(date)

    unpredicted_departures_query =
      from(ve in VehicleEvent,
        as: :vehicle_event,
        where:
          not is_nil(ve.trip_id) and
            not is_nil(ve.departure_time) and
            not ve.is_deleted and
            ve.environment == ^env and
            ve.departure_time >= ^min_time and
            ve.departure_time <= ^max_time and
            ve.route_id == ^route_id and
            ve.stop_id == ^stop_id and
            not exists(
              from(p in Prediction,
                where:
                  p.vehicle_event_id == parent_as(:vehicle_event).id and
                    p.file_timestamp < parent_as(:vehicle_event).departure_time and
                    not is_nil(p.departure_time)
              )
            ),
        order_by: [asc: ve.departure_time],
        select: {ve.vehicle_id, ve.trip_id, ve.departure_time}
      )

    unpredicted_departures_query
    |> PredictionAnalyzer.Repo.all()
    |> Enum.map(fn row ->
      {
        elem(row, 0),
        elem(row, 1),
        elem(row, 2) |> format_unix()
      }
    end)
  end

  def missed_departures_summary(date, env) do
    {min_time, max_time} = service_times(date)

    missed_departures_query =
      from(p in Prediction,
        where:
          p.environment == ^env and
            p.file_timestamp >= ^min_time and
            p.file_timestamp <= ^max_time and
            not is_nil(p.departure_time) and
            p.stop_id in ^terminal_stops(),
        group_by: p.route_id,
        select:
          {p.route_id, count(p.trip_id, :distinct),
           count(p.trip_id, :distinct) |> filter(is_nil(p.vehicle_event_id)),
           (count(p.trip_id, :distinct) |> filter(is_nil(p.vehicle_event_id))) * 100.0 /
             count(p.trip_id, :distinct)}
      )

    missed_departures_query
    |> PredictionAnalyzer.Repo.all()
    |> Enum.sort_by(&Map.get(sort_map(), elem(&1, 0), 0))
  end

  def missed_departures_for_route(date, env, route_id) do
    {min_time, max_time} = service_times(date)

    missed_departures_query =
      from(p in Prediction,
        where:
          p.environment == ^env and
            p.file_timestamp >= ^min_time and
            p.file_timestamp <= ^max_time and
            not is_nil(p.departure_time) and
            p.route_id == ^route_id and
            p.stop_id in ^terminal_stops(),
        group_by: p.stop_id,
        order_by: [desc: count(p.trip_id, :distinct)],
        select:
          {p.stop_id, count(p.trip_id, :distinct),
           count(p.trip_id, :distinct) |> filter(is_nil(p.vehicle_event_id)),
           (count(p.trip_id, :distinct) |> filter(is_nil(p.vehicle_event_id))) * 100.0 /
             count(p.trip_id, :distinct)}
      )

    PredictionAnalyzer.Repo.all(missed_departures_query) |> add_stop_names()
  end

  def missed_departures_for_route_stop(date, env, route_id, stop_id) do
    {min_time, max_time} = service_times(date)

    missed_departures_query =
      from(p in Prediction,
        where:
          p.environment == ^env and
            p.file_timestamp >= ^min_time and
            p.file_timestamp <= ^max_time and
            p.route_id == ^route_id and
            not is_nil(p.departure_time) and
            is_nil(p.vehicle_event_id) and
            p.stop_id == ^stop_id,
        group_by: [p.vehicle_id, p.trip_id],
        order_by: [p.vehicle_id, min(p.departure_time)],
        select:
          {p.vehicle_id, p.trip_id, min(p.departure_time), max(p.departure_time),
           min(p.file_timestamp), max(p.file_timestamp), count(p.id)}
      )

    missed_departures_query
    |> PredictionAnalyzer.Repo.all()
    |> Enum.map(fn row ->
      {
        elem(row, 0),
        elem(row, 1),
        elem(row, 2) |> format_unix(),
        elem(row, 3) |> format_unix(),
        elem(row, 4) |> format_unix(),
        elem(row, 5) |> format_unix(),
        elem(row, 6)
      }
    end)
  end

  defp service_times(date) do
    start_time = Time.new!(4, 0, 0)
    {:ok, start_date_time} = DateTime.new(date, start_time, "America/New_York")

    end_time = Time.new!(2, 0, 0)
    tomorrow = Date.add(date, 1)
    {:ok, end_date_time} = DateTime.new(tomorrow, end_time, "America/New_York")

    {start_date_time |> DateTime.to_unix(), end_date_time |> DateTime.to_unix()}
  end

  defp sort_map() do
    PredictionAnalyzer.Utilities.routes_for_mode(:subway) |> Enum.with_index() |> Enum.into(%{})
  end

  defp terminal_stops() do
    StopGroups.expand_groups(["_terminal"])
  end

  defp add_stop_names(data) do
    stop_dict = StopNameFetcher.get_stop_descriptions(:subway)

    Enum.map(data, fn row ->
      stop_id = elem(row, 0)
      stop_name = Map.get(stop_dict, stop_id, stop_id)
      Tuple.insert_at(row, 1, stop_name)
    end)
  end
end

lib/prediction_analyzer_web/controllers/missed_predictions_controller.ex
defmodule PredictionAnalyzerWeb.MissedPredictionsController do
  use PredictionAnalyzerWeb, :controller
  alias PredictionAnalyzer.StopNameFetcher
  alias PredictionAnalyzer.MissedPredictions

  defp parse_date(nil), do: Date.utc_today()

  defp parse_date(date_str) do
    case Date.from_iso8601(date_str) do
      {:ok, date} -> date
      {:error, _} -> DateTime.now!("America/New_York") |> DateTime.to_date()
    end
  end

  defp base_params(params) do
    date = parse_date(params["date"])
    env = params["env"] || "prod"

    Map.merge(params, %{
      date: date,
      env: env,
      query_params: params
    })
  end

  defp totals(data, base_idx, missed_idx) do
    total_missed = data |> Enum.map(&elem(&1, missed_idx)) |> Enum.sum()
    total_base = data |> Enum.map(&elem(&1, base_idx)) |> Enum.sum()
    total_pct = if total_base > 0, do: total_missed * 100.0 / total_base, else: 0.0
    {total_base, total_missed, total_pct}
  end

  defp load_data(
         %{"missing_route" => missing_route, "stop_id" => stop_id, env: env, date: date} = params
       )
       when not is_nil(missing_route) do
    stop_name = StopNameFetcher.get_stop_name(:subway, stop_id)

    Map.merge(params, %{
      missing_departures_for_route_stop:
        MissedPredictions.unpredicted_departures_for_route_stop(date, env, missing_route, stop_id),
      stop_name: stop_name,
      stop_id: stop_id,
      route: missing_route
    })
  end

  defp load_data(%{"missing_route" => missing_route, env: env, date: date} = params)
       when not is_nil(missing_route) do
    missing_departures_for_route =
      MissedPredictions.unpredicted_departures_for_route(date, env, missing_route)

    totals = totals(missing_departures_for_route, 2, 3)

    Map.merge(params, %{
      missing_departures_for_route:
        MissedPredictions.unpredicted_departures_for_route(date, env, missing_route),
      totals: totals,
      route: missing_route
    })
  end

  defp load_data(
         %{"missed_route" => missed_route, "stop_id" => stop_id, env: env, date: date} = params
       )
       when not is_nil(missed_route) do
    stop_name = StopNameFetcher.get_stop_name(:subway, stop_id)

    Map.merge(params, %{
      unrealized_departures_for_route_stop:
        MissedPredictions.missed_departures_for_route_stop(date, env, missed_route, stop_id),
      route: missed_route,
      stop_id: stop_id,
      stop_name: stop_name
    })
  end

  defp load_data(%{"missed_route" => missed_route, env: env, date: date} = params)
       when not is_nil(missed_route) do
    unrealized_departures_for_route =
      MissedPredictions.missed_departures_for_route(date, env, missed_route)

    totals = totals(unrealized_departures_for_route, 2, 3)

    Map.merge(params, %{
      unrealized_departures_for_route:
        MissedPredictions.missed_departures_for_route(date, env, missed_route),
      totals: totals,
      route: missed_route
    })
  end

  defp load_data(%{env: env, date: date} = params) do
    unpredicted_departures = MissedPredictions.unpredicted_departures_summary(date, env)
    missed_departures = MissedPredictions.missed_departures_summary(date, env)
    unpredicted_totals = totals(unpredicted_departures, 1, 2)
    missed_totals = totals(missed_departures, 1, 2)

    Map.merge(params, %{
      unpredicted_departures: unpredicted_departures,
      missed_departures: missed_departures,
      unpredicted_totals: unpredicted_totals,
      missed_totals: missed_totals
    })
  end

  def index(conn, params) do
    assigns =
      params
      |> base_params()
      |> load_data()

    conn =
      conn
      |> put_in(
        [Access.key(:params, %{}), Access.key("filters", %{}), Access.key("chart_range", %{})],
        "Missed/Missing Predictions"
      )
      |> put_in([Access.key(:params, %{}), "date"], Date.to_iso8601(assigns[:date]))

    render(conn, "index.html", assigns)
  end
end

lib/prediction_analyzer_web/views/missed_predictions_view.ex
defmodule PredictionAnalyzerWeb.MissedPredictionsView do
  use PredictionAnalyzerWeb, :view
end

lib/prediction_analyzer_web/templates/missed_predictions/index.html.eex
<%= render(PredictionAnalyzerWeb.PartialsView, "header.html", assigns) %>
<hr class="accuracy-separator">
<div id="content" class="row">

<%= form_for @conn, Routes.missed_predictions_path(@conn, :index), [method: :get, class: "filters-form", id: "filter-form"], fn f -> %>
  <div class="col-xs-3">
    <div class="accuracy-form-filters">
      <div class="form-group">
        <%= explainer_label(f, :date, "Date") %>
        <%= date_input(f, :date, class: "form-control") %>
      </div>
      <div class="form-group">
        <%= explainer_label(f, :env, "Environment") %>
        <%= select(f, :env, ["Prod": "prod", "Dev Green": "dev-green", "Dev Blue": "dev-blue"], class: "form-control") %>
      </div>
      <%= submit "Filter", id: "filter-submit-btn", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

<div class="col-xs-9">
  <%= form_for @conn, Routes.accuracy_path(@conn, :index), [as: "filters", method: :get, class: "accuracy-form", id: "accuracy-form", action: "/accuracy"], fn f -> %>
  <%= render(PredictionAnalyzerWeb.PartialsView, "chart_selection_boxes.html", %{f: f, conn: @conn}) %>
  <% end %>
  <div class=row>
    <%= cond do %>
    <% assigns[:missing_departures_for_route_stop] -> %>
      <%= link("Back to overview", to: Routes.missed_predictions_path(@conn, :index, @query_params |> Map.delete("missing_route") |> Map.delete("stop_id"))) %>
      <%= render("missing_departures_for_route_stop.html", assigns) %>
    <% assigns[:missing_departures_for_route] -> %>
      <%= link("Back to overview", to: Routes.missed_predictions_path(@conn, :index, Map.delete(@query_params, "missing_route"))) %>
      <%= render("missing_departures_for_route.html", assigns) %>
    <% assigns[:unrealized_departures_for_route_stop] -> %>
      <%= link("Back to overview", to: Routes.missed_predictions_path(@conn, :index, @query_params |> Map.delete("missed_route") |> Map.delete("stop_id"))) %>
      <%= render("unrealized_departures_for_route_stop.html", assigns) %>
    <% assigns[:unrealized_departures_for_route] -> %>
      <%= link("Back to overview", to: Routes.missed_predictions_path(@conn, :index, Map.delete(@query_params, "missed_route"))) %>
      <%= render("unrealized_departures_for_route.html", assigns) %>
    <% true -> %>
      <%= render("summary_tables.html", assigns) %>
    <% end %>
  </div>
</div>
</div>

lib/prediction_analyzer_web/templates/missed_predictions/missing_departures_by_route.html.eex
<div class="col-sm-12">
<h3>Unpredicted Departures</h3>
<h4><%= @route %> - All Stops</h4>
<table class="table">
    <thead>
    <tr>
        <th>Stop ID</th>
        <th>Stop Name</th>
        <th>Total Departures</th>
        <th>Unpredicted Departures</th>
        <th>Percentage</th>
    </tr>
    </thead>
    <tbody>
    <%= for {stop_id, stop_name, total, unpredicted, pct} <- @missing_departures_by_route do %>
    <tr>
        <td><%= link(stop_id, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "stop_id", stop_id))) %></td>
        <td><%= link(stop_name, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "stop_id", stop_id))) %></td>
        <td><%= total %></td>
        <td><%= unpredicted %></td>
        <td><%= :erlang.float_to_binary(pct, [decimals: 2]) %></td>
    </tr>
    <% end %>
    <tr>
        <% total_departures = @missing_departures_by_route |> Enum.map(&(elem(&1, 2))) |> Enum.sum() %>
        <% total_unpredicted = @missing_departures_by_route |>  Enum.map(&(elem(&1, 3))) |> Enum.sum() %>
        <% total_pct = if total_departures > 0, do: (total_unpredicted / total_departures) * 100, else: 0.0 %>
        <td></td>
        <td>Total</td>
        <td><strong><%= total_departures %></strong></td>
        <td><strong><%= total_unpredicted %></strong></td>
        <td><strong><%= :erlang.float_to_binary(total_pct, [decimals: 2]) %></strong></td>
    </tr>
    </tbody>
</table>
</div>

lib/prediction_analyzer_web/templates/missed_predictions/missing_departures_by_route_stop.html.eex
<div class="col-sm-12">
    <h3>Unpredicted Departures</h3>
    <h4><%= @route %> - <%= @stop_name %> (<%= @stop_id %>)</h4>
    <table class="table">
    <thead>
        <tr>
        <th>Vehicle</th>
        <th>Trip</th>
        <th>Departure Time</th>
        </tr>
    </thead>
    <tbody>
        <%= for {vehicle_id, trip_id, departure_time} <- @missing_departures_by_route_stop do %>
        <tr>
            <td><%= vehicle_id %></td>
            <td><%= trip_id %></td>
            <td><%= format_unix(departure_time) %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>

lib/prediction_analyzer_web/templates/missed_predictions/missing_departures_for_route.html.eex
<div class="col-sm-12">
<h3>Unpredicted Departures</h3>
<h4><%= @route %> - All Stops</h4>
<table class="table">
    <thead>
    <tr>
        <th>Stop ID</th>
        <th>Stop Name</th>
        <th>Total Departures</th>
        <th>Unpredicted Departures</th>
        <th>Percentage</th>
    </tr>
    </thead>
    <tbody>
    <%= for {stop_id, stop_name, total, unpredicted, pct} <- @missing_departures_for_route do %>
    <tr>
        <td><%= link(stop_id, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "stop_id", stop_id))) %></td>
        <td><%= link(stop_name, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "stop_id", stop_id))) %></td>
        <td><%= total %></td>
        <td><%= unpredicted %></td>
        <td><%= :erlang.float_to_binary(pct, [decimals: 2]) %></td>
    </tr>
    <% end %>
    <tr>
        <% {total_departures, total_unpredicted, total_pct} = @totals %>
        <td></td>
        <td>Total</td>
        <td><strong><%= total_departures %></strong></td>
        <td><strong><%= total_unpredicted %></strong></td>
        <td><strong><%= :erlang.float_to_binary(total_pct, [decimals: 2]) %></strong></td>
    </tr>
    </tbody>
</table>
</div>

lib/prediction_analyzer_web/templates/missed_predictions/missing_departures_for_route_stop.html.eex
<div class="col-sm-12">
    <h3>Unpredicted Departures</h3>
    <h4><%= @route %> - <%= @stop_name %> (<%= @stop_id %>)</h4>
    <table class="table">
    <thead>
        <tr>
        <th>Vehicle</th>
        <th>Trip</th>
        <th>Departure Time</th>
        </tr>
    </thead>
    <tbody>
        <%= for {vehicle_id, trip_id, departure_time} <- @missing_departures_for_route_stop do %>
        <tr>
            <td><%= vehicle_id %></td>
            <td><%= trip_id %></td>
            <td><%= departure_time %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>

lib/prediction_analyzer_web/templates/missed_predictions/summary_tables.html.eex
<div class="col-sm-6">
<h3>Unpredicted Departures</h3>
<table class="table">
    <thead>
    <tr>
        <th>Route</th>
        <th>Total Departures</th>
        <th>Unpredicted Departures</th>
        <th>Percentage</th>
    </tr>
    </thead>
    <tbody>
    <%= for {route, total, unpredicted, pct} <- @unpredicted_departures do %>
    <tr>
        <td><%= link(route, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "missing_route", route))) %></td>
        <td><%= total %></td>
        <td><%= unpredicted %></td>
        <td><%= :erlang.float_to_binary(pct, [decimals: 2]) %></td>
    </tr>
    <% end %>
    <tr>
        <% {total_departures, total_unpredicted, total_pct} = @unpredicted_totals %>
        <td><strong>Total</strong></td>
        <td><strong><%= total_departures %></strong></td>
        <td><strong><%= total_unpredicted %></strong></td>
        <td><strong><%= :erlang.float_to_binary(total_pct, [decimals: 2]) %></strong></td>
    </tr>
    </tbody>
</table>
</div>

<div class="col-sm-6">
<h3>Unrealized Departure Predictions</h3>
<table class="table">
    <thead>
    <tr>
        <th>Route</th>
        <th>Total Trips</th>
        <th>Trips With Unrealized Departures</th>
        <th>Percentage</th>
    </tr>
    </thead>
    <tbody>
    <%= for {route, total, unrealized, pct} <- @missed_departures do %>
    <tr>
        <td><%= link(route, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "missed_route", route))) %></td>
        <td><%= total %></td>
        <td><%= unrealized %></td>
        <td><%= :erlang.float_to_binary(pct, [decimals: 2]) %></td>
    </tr>
    <% end %>
    <tr>
        <% {total_trips, total_unrealized, total_pct} = @missed_totals %>
        <td><strong>Total</strong></td>
        <td><strong><%= total_trips %></strong></td>
        <td><strong><%= total_unrealized %></strong></td>
        <td><strong><%= :erlang.float_to_binary(total_pct, [decimals: 2]) %></strong></td>
    </tr>
    </tbody>
</table>
</div>

lib/prediction_analyzer_web/templates/missed_predictions/unrealized_departures_by_route.html.eex
<div class="col-sm-12">
<h3>Unrealized Departure Predictions</h3>
<h4><%= @route %> - All Stops</h4>
<table class="table">
    <thead>
    <tr>
        <th>Stop ID</th>
        <th>Stop Name</th>
        <th>Total Trips</th>
        <th>Trips With Unrealized Departures</th>
        <th>Percentage</th>
    </tr>
    </thead>
    <tbody>
    <%= for {stop_id, stop_name, total, unrealized, pct} <- @unrealized_departures_by_route do %>
    <tr>
        <td><%= link(stop_id, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "stop_id", stop_id))) %></td>
        <td><%= link(stop_name, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "stop_id", stop_id))) %></td>
        <td><%= total %></td>
        <td><%= unrealized %></td>
        <td><%= :erlang.float_to_binary(pct, [decimals: 2]) %></td>
    </tr>
    <% end %>
    <tr>
        <% total_trips = @unrealized_departures_by_route |> Enum.map(&(elem(&1, 2))) |> Enum.sum() %>
        <% total_unrealized = @unrealized_departures_by_route |>  Enum.map(&(elem(&1, 3))) |> Enum.sum() %>
        <% total_pct = if total_trips > 0, do: (total_unrealized / total_trips) * 100, else: 0.0 %>
        <td></td>
        <td>Total</td>
        <td><strong><%= total_trips %></strong></td>
        <td><strong><%= total_unrealized %></strong></td>
        <td><strong><%= :erlang.float_to_binary(total_pct, [decimals: 2]) %></strong></td>
    </tr>
    </tbody>
</table>
</div>

lib/prediction_analyzer_web/templates/missed_predictions/unrealized_departures_by_route_stop.html.eex
<div class="col-sm-12">
    <h3>Unrealized Departure Predictions</h3>
    <h4><%= @route %> - <%= @stop_name %> (<%= @stop_id %>)</h4>
    <table class="table">
    <thead>
        <tr>
        <th>Vehicle ID</th>
        <th>Trip ID</th>
        <th>Min Departure Time</th>
        <th>Max Departure Time</th>
        <th>Min File Time</th>
        <th>Max File Time</th>
        <th>Total Predictions</th>
        </tr>
    </thead>
    <tbody>
        <%= for {vehicle_id, trip_id, min_departure_time, max_departure_time, min_file_time, max_file_time, predictions} <- @unrealized_departures_by_route_stop do %>
        <tr>
        <td><%= vehicle_id %></td>
        <td><%= trip_id %></td>
        <td><%= format_unix(min_departure_time) %></td>
        <td><%= format_unix(max_departure_time) %></td>
        <td><%= format_unix(min_file_time) %></td>
        <td><%= format_unix(max_file_time) %></td>
        <td><%= predictions %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>

lib/prediction_analyzer_web/templates/missed_predictions/unrealized_departures_for_route.html.eex
<div class="col-sm-12">
<h3>Unrealized Departure Predictions</h3>
<h4><%= @route %> - All Stops</h4>
<table class="table">
    <thead>
    <tr>
        <th>Stop ID</th>
        <th>Stop Name</th>
        <th>Total Trips</th>
        <th>Trips With Unrealized Departures</th>
        <th>Percentage</th>
    </tr>
    </thead>
    <tbody>
    <%= for {stop_id, stop_name, total, unrealized, pct} <- @unrealized_departures_for_route do %>
    <tr>
        <td><%= link(stop_id, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "stop_id", stop_id))) %></td>
        <td><%= link(stop_name, to: Routes.missed_predictions_path(@conn, :index, Map.put(@query_params, "stop_id", stop_id))) %></td>
        <td><%= total %></td>
        <td><%= unrealized %></td>
        <td><%= :erlang.float_to_binary(pct, [decimals: 2]) %></td>
    </tr>
    <% end %>
    <tr>
        <% {total_trips, total_unrealized, total_pct} = @totals %>
        <td></td>
        <td>Total</td>
        <td><strong><%= total_trips %></strong></td>
        <td><strong><%= total_unrealized %></strong></td>
        <td><strong><%= :erlang.float_to_binary(total_pct, [decimals: 2]) %></strong></td>
    </tr>
    </tbody>
</table>
</div>

lib/prediction_analyzer_web/templates/missed_predictions/unrealized_departures_for_route_stop.html.eex
<div class="col-sm-12">
    <h3>Unrealized Departure Predictions</h3>
    <h4><%= @route %> - <%= @stop_name %> (<%= @stop_id %>)</h4>
    <table class="table">
    <thead>
        <tr>
        <th>Vehicle ID</th>
        <th>Trip ID</th>
        <th>Min Departure Time</th>
        <th>Max Departure Time</th>
        <th>Min File Time</th>
        <th>Max File Time</th>
        <th>Total Predictions</th>
        </tr>
    </thead>
    <tbody>
        <%= for {vehicle_id, trip_id, min_departure_time, max_departure_time, min_file_time, max_file_time, predictions} <- @unrealized_departures_for_route_stop do %>
        <tr>
        <td><%= vehicle_id %></td>
        <td><%= trip_id %></td>
        <td><%= min_departure_time %></td>
        <td><%= max_departure_time %></td>
        <td><%= min_file_time %></td>
        <td><%= max_file_time %></td>
        <td><%= predictions %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>